
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'hakkoda_edw_data_vault'
version: '1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring dbt_artifacts logging in production for observability
#on-run-end: "{% if target.name == 'prod' %}{{ dbt_artifacts.upload_results(results) }}{% endif %}"
on-run-end: "{{ dbt_artifacts.upload_results(results) }}"

# Configuring tests
tests:
  +store_failures: true
  +schema: test_results

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  hakkoda_edw_data_vault:
    raw_stage:
      +materialized: view
      +schema: 'raw_stage' 
    hash_stage:
      +materialized: view
      +schema: 'hash_stage'       
    raw_vault:
      +materialized: incremental 
      +schema: 'raw_vault' 
      +persist_docs:
        relation: true
        columns: true
    biz_vault:
      +materialized: view
      +schema: 'biz_vault' 
      +persist_docs:
        relation: true
        columns: true      
    info_mart:
      +materialized: view
      +schema: 'info_mart'  
      +persist_docs:
        relation: true
        columns: true        
    source_mart:
      +materialized: view
      +schema: 'source_mart'  
    unit_test:
      +materialized: view
      +schema: 'unit_test'
    observability:
      +materialized: view
      +schema: 'observability'      
  dbt_artifacts:
    +schema: dbt_artifacts # optional, default is your target schema
    staging:
      +schema: dbt_artifacts_staging # optional, default is your target schema
    sources:
      +schema: dbt_artifacts_sources # optional, default is your target schema  

vars:
  hash: MD5
  'dbt_date:time_zone': 'America/Los_Angeles'
  is_incremental: true
  _fivetran_synced_local: 'CONVERT_TIMEZONE(''UTC'',''America/Los_Angeles'', _FIVETRAN_SYNCED)'
  enable_ghost_records: true
  system_record_value: 'DBTVAULT_SYSTEM' # Record Source value for ghost records in satellites 

